id: P390C3020
initial_creation_type: input
source_metadata:
  title: Do Khyentse Yeshe Dorje Series
  language: en
  description: 'A series of texts associated with the treasure-revealer Do Khyentse
    Yeshe Dorje (mdo mkhyen brtse ye shes rdo rje, 1800–1866), renowned as the ''mind
    emanation'' of Jigme Lingpa:'
  volume:
    5dabf935cdc44d81a8e8aa90c19a4e06:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Aspiration Prayers
    349b5db96130493981667160181384c8:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    01304d2392cf469894441169fe05ce2a:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Guru Rinpoche Prayers
    aa830d0cd0fa4c6d9134d2c787aecfc9:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Guru Rinpoche Prayers
    5039ec659d0b44d791a65bf4719ac5db:
      title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
      parent: Lineage Prayers
    8e12ffc21a404261ba505844bc9f838d:
      title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and
        Liberation of Rigdzin Jalü Dorje'
      parent: Prayers
    8dacc7b9e59246fcb134ba82b3439d88:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Preliminaries
created_at: '2022-02-28T22:55:14.998519'
last_modified_at: '2022-02-28T22:55:14.998525'
